#!/usr/bin/env python3
import os
import runpy
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(ROOT, "src"))

sys.argv[0] = os.path.join(ROOT, "src", "triadc")
runpy.run_path(sys.argv[0], run_name="__main__")
