#!/usr/bin/env python3
import os
import runpy
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PY_ROOT = os.path.join(ROOT, "python")
sys.path.insert(0, PY_ROOT)

sys.argv[0] = os.path.join(PY_ROOT, "triadc")
runpy.run_path(sys.argv[0], run_name="__main__")
