#!/usr/bin/env python3
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
PY_ROOT = os.path.join(ROOT, "python")
sys.path.insert(0, PY_ROOT)

from cli.main import main

sys.exit(main())
