from runtime.ml.data import DataLoader, Dataset
from runtime.ml.generate import GenerationResult, StreamToken, chat, generate, stream_generate
from runtime.ml.kinetic_surrogate import KineticSurrogate, hybrid_step
from runtime.ml.language import CharTokenizer, TextDataset, TriadLM, TriadtriadBlock, TriadtriadLM
from runtime.ml.losses import (
    bce_loss,
    binary_cross_entropy_with_logits,
    cosine_similarity_loss,
    huber_loss,
    kl_div,
    l1_loss,
    nll_loss,
    smooth_l1_loss,
)
from runtime.ml.metrics import (
    accuracy,
    confusion_matrix,
    mean_absolute_error,
    perplexity,
    precision_recall_f1,
    r2_score,
    root_mean_squared_error,
    top_k_accuracy,
)
from runtime.ml.model_loader import (
    TriadModel,
    TriadModelGGUF,
    TriadTokenizer,
    load_model,
    load_tokenizer,
)
from runtime.ml.nn import (
    ELU,
    GELU,
    GRU,
    LSTM,
    RNN,
    SGD,
    Adam,
    AdamW,
    AdaptiveAvgPool1d,
    AvgPool1d,
    AvgPool2d,
    BatchNorm1d,
    Conv1d,
    Conv2d,
    CrossAttention,
    Dropout,
    Embedding,
    FeedForward,
    Flatten,
    GlobalAvgPool,
    GroupNorm,
    LayerNorm,
    LeakyReLU,
    MaxPool1d,
    MaxPool2d,
    Module,
    MultiHeadAttention,
    Parameter,
    ReLU,
    ResidualBlock,
    RMSNorm,
    Sequential,
    Sigmoid,
    SiLU,
    Softmax,
    Tanh,
    Transformer,
    TransformerBlock,
    TransformerDecoderBlock,
    TriadSSM,
    TriadSSMBlock,
    kaiming_normal,
    kaiming_uniform,
    triad,
    xavier_normal,
    xavier_uniform,
)
from runtime.ml.param_bridge import ParamBridge, triadblock_bridge
from runtime.ml.param_bridge import ssm_bridge as triadssm_bridge
from runtime.ml.physics_ml import (
    BoundaryLoss,
    ConservationLoss,
    FourierFeatures,
    FourierNeuralOperator,
    HamiltonianLayer,
    PhysicsInformedMLP,
    SpectralConv1d,
    TriadNeuralOperator,
    TriadResidualLoss,
)
from runtime.ml.serialization import load_checkpoint, load_weights, save_checkpoint, save_weights
from runtime.ml.solver_grad_bridge import (
    SolverGradContext,
    no_solver_grad,
    solver_grad_step,
    wrap_grad_fn_with_solver,
)
from runtime.ml.surrogate import (
    FidelityGate,
    MNOSurrogate,
    TriadContext,
    accelerated_rollout,
    train_surrogate,
)
from runtime.ml.tensor import (
    TriadTensor,
    arange,
    bmm,
    cat,
    cos,
    cross_entropy,
    exp,
    eye,
    layer_norm,
    linspace,
    log,
    mse_loss,
    no_grad,
    ones,
    rand,
    randn,
    relu,
    sigmoid,
    sin,
    softmax,
    sqrt,
    stack,
    tanh,
    tensor,
    transpose,
    zeros,
)
from runtime.ml.trainer import (
    SWA,
    CosineAnnealingLR,
    EarlyStopping,
    GradientAccumulation,
    GradientClipping,
    LambdaScheduler,
    LossHistory,
    LRScheduler,
    MixedPrecision,
    ModelCheckpoint,
    OneCycleLR,
    Trainer,
    WarmupCosineScheduler,
)
